### ISSUE TITLE
is it ok to pub personal information on github?

### ISSUE THREAD

**Issue by VictorLlu** [wznmickey/rhapsodia#2]
麻烦您把有关个人信息的文件撤一下好吗

**Comment by wznmickey** [comment]
非常抱歉刚刚才注意到。

　　公开的部分为登记的名字及加密处理过的对应的手机号。由于技术部的能力、资金和时间问题，很抱歉我们无法将有关数据存储在自己的服务器内进行前后端分离，所以所有访问网址的用户均可读取全部的数据列表，这不是存储在github上的问题，放在其他地方也存在同样的问题。
　　在得到负责人的同意后，这些信息会被删除。

**Comment by wznmickey** [comment]
已经删除
